name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Расписание: каждая среда в 12:30 и каждая пятница в 22:00 (UTC)
    - cron: "30 12 * * 3"
    - cron: "00 22 * * 5"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java ${{ matrix.java }} on ${{ matrix.os }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'

    - name: Grant execute permissions for gradlew (Linux/MacOS only)
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test
